// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH2cUswfLIyOMB-OGwNUVy2d9_I0zMnHc',
    appId: '1:848417511217:android:81ba5ad2822208f3fc0210',
    messagingSenderId: '848417511217',
    projectId: 'to-do-itbee',
    storageBucket: 'to-do-itbee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABxsxNUbT9iIV7_gPjJWv51jxFet1kN_c',
    appId: '1:848417511217:ios:29613a8c8c1ae223fc0210',
    messagingSenderId: '848417511217',
    projectId: 'to-do-itbee',
    storageBucket: 'to-do-itbee.firebasestorage.app',
    iosBundleId: 'com.todoitbee.dang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABxsxNUbT9iIV7_gPjJWv51jxFet1kN_c',
    appId: '1:848417511217:ios:776f1e5719436681fc0210',
    messagingSenderId: '848417511217',
    projectId: 'to-do-itbee',
    storageBucket: 'to-do-itbee.firebasestorage.app',
    iosBundleId: 'com.example.toDoItbee',
  );
}
